### ISSUE TITLE
Nothing in Blender

### ISSUE THREAD

**Issue by yunusemrecan** [sukhmeetbawa/OpenCL-AMD-Fedora#1]
I followed the instuctions and got the clinfo screen, just like you I got 3500u, but no change on blender

**Comment by sukhmeetbawa** [comment]
You will need to use blender version before 3.0.0 because in 3.0.0, they don't support OpenCL in favour for HIP. you can read more about this [here](https://code.blender.org/2021/11/next-level-support-for-amd-gpus/).
