### ISSUE TITLE
Potential regEx issue (my fault)

### ISSUE THREAD

**Issue by PimpinPumpkin** [sukhmeetbawa/OpenCL-AMD-Fedora#10]
Reposting this here for visibility.

I don't know at all what the contents of `/etc/yum.repos.d/rocm.repo` look like, so I took a fairly safe shot in the dark as to how to make the code dynamic. Perhaps you have a dump of the file so I can see what to look for? If there are other occurrences of the phrase `rhelsomeNumber/someNumber`, my changes will interfere with those. I have a solution just in case, but a dump of the file would be great.

**Comment by sukhmeetbawa** [comment]
[rocm]
name=ROCm 5.2 repository
baseurl=https://repo.radeon.com/rocm/yum/latest/main
enable=1
gpgcheck=1
priority=50
gpgkey=file:///etc/amdgpu-install/rocm.gpg.key

**Comment by PimpinPumpkin** [comment]
Perfect, thanks. The script shouldn't have any issues then. I over-engineered it not knowing how big or complex it would be.
