### ISSUE TITLE
Installing progl hangs

### ISSUE THREAD

**Issue by chinh4thepro** [sukhmeetbawa/OpenCL-AMD-Fedora#15]
` [chinh4thepro@pog OpenCL-AMD-Fedora]$ ./opencl-amd.sh

Legacy Drivers are are required for Arctic Islands/Polaris
Latest Drivers work with Vega and Above

1) Install-OpenCL-Latest   4) Install-Portable-ProGL  7) Uninstall-ProGL
2) Install-OpenCL-Legacy   5) Patch-Davinci-Resolve   8) Quit
3) Install-HIP-Latest	   6) Uninstall-OpenCL
Enter Option Number: 4
Installing Portable ProGL
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   750    0   750    0     0   3235      0 --:--:-- --:--:-- --:--:--  3246
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1641    0  1641    0     0  12304      0 --:--:-- --:--:-- --:--:-- 12338
Downloading Dependencies
Repository WineHQ is listed more than once in the configuration
Last metadata expiration check: 1:42:42 ago on Tue 26 Jul 2022 06:41:54 PM EDT.
Package cpio-2.13-12.fc36.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
Downloading Drivers
#=#=-#
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   750    0   750    0     0   9580      0 --:--:-- --:--:-- --:--:--  9615
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1641    0  1641    0     0  21744      0 --:--:-- --:--:-- --:--:-- 21880
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   750    0   750    0     0   4669      0 --:--:-- --:--:-- --:--:--  4658
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1641    0  1641    0     0  12056      0 --:--:-- --:--:-- --:--:-- 12066
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   750    0   750    0     0   4841      0 --:--:-- --:--:-- --:--:--  4870
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1641    0  1641    0     0   5445      0 --:--:-- --:--:-- --:--:--  5451
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   750    0   750    0     0   3862      0 --:--:-- --:--:-- --:--:--  3865
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1641    0  1641    0     0   8314      0 --:--:-- --:--:-- --:--:--  8287
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   750    0   750    0     0   2550      0 --:--:-- --:--:-- --:--:--  2559
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1641    0  1641    0     0   8420      0 --:--:-- --:--:-- --:--:--  8458
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   750    0   750    0     0   5685      0 --:--:-- --:--:-- --:--:--  5725
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1641    0  1641    0     0   3009      0 --:--:-- --:--:-- --:--:--  3005
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   750    0   750    0     0  10215      0 --:--:-- --:--:-- --:--:-- 10273
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1641    0  1641    0     0  20978      0 --:--:-- --:--:-- --:--:-- 21038
index.html                [ <=>                      ]   6.74K  --.-KB/s    in 0s
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   750    0   750    0     0   9952      0 --:--:-- --:--:-- --:--:-- 10000
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1641    0  1641    0     0  21696      0 --:--:-- --:--:-- --:--:-- 21880
index.html                [ <=>                      ]   6.74K  --.-KB/s    in 0s
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   750    0   750    0     0   8338      0 --:--:-- --:--:-- --:--:--  8426
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1641    0  1641    0     0  21350      0 --:--:-- --:--:-- --:--:-- 21592
index.html                [ <=>                      ]   6.74K  --.-KB/s    in 0s
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   750    0   750    0     0  10017      0 --:--:-- --:--:-- --:--:-- 10135
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1641    0  1641    0     0  20965      0 --:--:-- --:--:-- --:--:-- 21038
index.html                [ <=>                      ]   6.74K  --.-KB/s    in 0s
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   750    0   750    0     0   9914      0 --:--:-- --:--:-- --:--:-- 10000
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1641    0  1641    0     0  21742      0 --:--:-- --:--:-- --:--:-- 21880
index.html                [ <=>                      ]   6.74K  --.-KB/s    in 0s
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   750    0   750    0     0  10008      0 --:--:-- --:--:-- --:--:-- 10000
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1641    0  1641    0     0  21264      0 --:--:-- --:--:-- --:--:-- 21311
index.html                [ <=>                      ]   6.74K  --.-KB/s    in 0s `

not sure if its my wifi's fault or something else

**Comment by PimpinPumpkin** [comment]
Thanks for the bug report and console output. I'm on vacation right now, but I'll try and find time to take a look at this. From the looks of it, the urls to the OpenGL drivers are broken. I will advise
