### ISSUE TITLE
No amdgpu-proprietary.repo when installing Portable-ProGL

### ISSUE THREAD

**Issue by oleg-rom** [sukhmeetbawa/OpenCL-AMD-Fedora#20]
Hello, I am tring to install amd drivers on my fedora 37 to work with Davinci Resolve using this tutorial. I am following the steps in the installation notes. So whenever I try in install Portable-ProGL or Patch-Davinci-Resolve, I get the same kind of error in both cases:

```
Enabling Proprietary AMD Repository
sed: cannot read /etc/yum.repos.d/amdgpu-proprietary.repo: no such file or catalog
```
So it cannot install ProGL and I can't find it here:

```
$HOME/.amdgpu-progl-portable
```
My card is AMD RX570, so I am using legacy drivers. Here are my steps of installation:

```
1. Install-OpenCL-Legacy
2. Install-Portable-ProGL
3. Reboot
4. Install Davinci Resolve 18
5. Patch-Davinci-Resolve
```

On #2 and #5 I get the same error, described earlier - there is no amdgpu-proprietary.repo.

Please help me to solve the problem.

Is there a problem with the script, or am I doing something wrong? Where do I get this amd gpu proprietary repo?

**Comment by sukhmeetbawa** [comment]
The proGL part in the script wasn't written with legacy GPUs in mind. I will add it in a few days.

**Comment by oleg-rom** [comment]
Thank you! That will be a great help!
