### ISSUE TITLE
install hip runtime not working fedora 37

### ISSUE THREAD

**Issue by meepcat55** [sukhmeetbawa/OpenCL-AMD-Fedora#21]
error
Installing HIP Runtime
Last metadata expiration check: 0:00:02 ago on Thu 08 Dec 2022 02:01:14 PM CST.
Package amdgpu-core-shim-0-1.fc37.x86_64 is already installed.
Error: 
 Problem: package hip-runtime-amd-5.4.22801.50400-72.el7.x86_64 requires comgr >= 2.0, but none of the providers can be installed
  - conflicting requests
  - nothing provides libtinfo.so.5()(64bit) needed by comgr-2.4.0.50400-72.el7.x86_64
(try to add '--skip-broken' to skip uninstallable packages)

**Comment by Vitorvlv** [comment]
Exact same error when trying to install OpenCL-Latest. I'm also on Fedora 37.

**Comment by swinzy** [comment]
@sukhmeetbawa Hey I can install it on Fedora 37 but Blender will not identify HIP. Any idea?
I've tried 
```
export LD_LIBRARY_PATH=/opt/rocm/lib/:$LD_LIBRARY_PATH
export PATH=$PATH:/opt/rocm/bin:/opt/rocm/profiler/bin:/opt/rocm/opencl/bin/x86_64
```
but had no luck.
