### ISSUE TITLE
Legacy install broken after 3f2040c

### ISSUE THREAD

**Issue by mcv100** [sukhmeetbawa/OpenCL-AMD-Fedora#5]
3f2040c6d688c1e2b953954e91af63e2ca0aef63 removed the `buildWorkaround()` command, which leaves the legacy install option broken.

I simply reverted to the commit before that (8f49df5fffb973c5b490ce5dd115374ca1010eb1) and installing for my RX480 works fine now.

Perhaps you can fix this for future legacy users?

**Comment by sukhmeetbawa** [comment]
Thanks for telling. I have fixed it now.
