### ISSUE TITLE
Updating Legacy OpenCL driver version

### ISSUE THREAD

**Issue by PimpinPumpkin** [sukhmeetbawa/OpenCL-AMD-Fedora#7]
In versions 21.40 and later, AMD changed the way they distributed their drivers on Linux.

I tried for several hours to figure out how to update the script to use newer drivers when installing with option 2 (Legacy OpenCL), but it seems many package names have changed, or I just can't locate them within repo.radeon.com. Honestly, I'm a bit surprised the script even works at all, considering for legacy installs it's pulling version 21.30, which isn't even visible on AMD's repo anymore.

Am I missing something? I'm happy to contribute in any way if you need my assistance.

Thank you for all your good work!

**Comment by sukhmeetbawa** [comment]
The legacy drivers are for polaris GPU as AMD has ended support for them but many people still have it so the script installs the last supported drivers for them.

**Comment by PimpinPumpkin** [comment]
Really? When I try to download drivers on AMD.com and select my GPU (RX 580), it shows 22.20 as a compatible version, and prompts me to download it. Polaris came out only like 6 years ago, so I'd be surprised if they stopped supporting them already.

**Comment by sukhmeetbawa** [comment]
Yeah, you can read more about it  [here](https://www.techpowerup.com/288864/amd-rocm-4-5-drops-polaris-architecture-support). Or checkout issue #2.

**Comment by PimpinPumpkin** [comment]
Thank you very much for the links. I can't believe AMD did that. How scummy! I feel old now even though my GPU isn't *that* old. Closing this issue now.
