### ISSUE TITLE
Potential issue when fixing ROCm repositories

### ISSUE THREAD

**Issue by PimpinPumpkin** [sukhmeetbawa/OpenCL-AMD-Fedora#8]
I'm unsure of what line 30 is trying to do:

`sed -i 's|rhel9/5.2|yum/latest|g' /etc/yum.repos.d/rocm.repo`

Is this property `sed` syntax? I've never seen a `sed` expression use pipes to delineate find and replace sections.

In any case, on my branch I've added `$latestROCm` to `getVersions()`, which should allow this line to be more dynamic. `$latestROCm` currently returns `5.2.0`. Below is a link this commit on my repo if you'd like to see how this works. I'll create a pull request on this branch once I understand how the above line of `sed` is supposed to function.

https://github.com/sukhmeetbawa/OpenCL-AMD-Fedora/commit/52b43da04e2d1892b940ff396098e33bef3be987

**Comment by sukhmeetbawa** [comment]
Well you can read about it [here](https://linuxize.com/post/how-to-use-sed-to-find-and-replace-string-in-files/). On this page there is mentioned the use of '|'.

**Comment by PimpinPumpkin** [comment]
Man, I'm learning a lot from you. Thanks! I'll submit a new pull request to make that line more update resilient in a moment. Closing out this issue.
